name: "app-network"

version: 1.0.0

client:
  organization: Org1
  logging:
    level: info
  cryptoconfig:
    path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config
  credentialStore:
    path: /tmp/app-store
    cryptoStore:
      path: /tmp/app-msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org1.cfginfo.com/users/User1@org1.cfginfo.com/tls/client.key
      cert:
        path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org1.cfginfo.com/users/User1@org1.cfginfo.com/tls/client.crt


channels:
  mychannel:

    peers:
      peer0.org1.cfginfo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org1.cfginfo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.cfginfo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org2.cfginfo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 10
        peerMonitorPeriod: 5s


organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.cfginfo.com/users/{userName}@org1.cfginfo.com/msp
    peers:
      - peer0.org1.cfginfo.com
      - peer1.org1.cfginfo.com
    certificateAuthorities:
      - ca.org1.cfginfo.com

  Org2:
    mspid: Org2MSP
    cryptoPath: peerOrganizations/org2.cfginfo.com/users/{userName}@org2.cfginfo.com/msp
    peers:
      - peer0.org2.cfginfo.com
      - peer1.org2.cfginfo.com
    certificateAuthorities:
      - ca.org2.cfginfo.com

  OrdererOrg:
    mspid: OrdererMSP
    cryptoPath: ordererOrganizations/cfginfo.com/users/{username}@cfginfo.com/msp
    orderers:
      - orderer0.cfginfo.com
      - orderer1.cfginfo.com
      - orderer2.cfginfo.com


orderers:
  orderer0.cfginfo.com:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/ordererOrganizations/cfginfo.com/orderers/orderer0.cfginfo.com/msp/tlscacerts/tlsca.cfginfo.com-cert.pem

  orderer1.cfginfo.com:
    url: localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer1.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/ordererOrganizations/cfginfo.com/orderers/orderer1.cfginfo.com/msp/tlscacerts/tlsca.cfginfo.com-cert.pem

  orderer2.cfginfo.com:
    url: localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer2.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/ordererOrganizations/cfginfo.com/orderers/orderer2.cfginfo.com/msp/tlscacerts/tlsca.cfginfo.com-cert.pem


peers:
  peer0.org1.cfginfo.com:
    url: localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org1.cfginfo.com/tlsca/tlsca.org1.cfginfo.com-cert.pem

  peer1.org1.cfginfo.com:
    url: localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org1.cfginfo.com/tlsca/tlsca.org1.cfginfo.com-cert.pem

  peer0.org2.cfginfo.com:
    url: localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org2.cfginfo.com/tlsca/tlsca.org2.cfginfo.com-cert.pem

  peer1.org2.cfginfo.com:
    url: localhost:10051
    grpcOptions:
      ssl-target-name-override: peer1.org2.cfginfo.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org2.cfginfo.com/tlsca/tlsca.org2.cfginfo.com-cert.pem


certificateAuthorities:
  ca.org1.cfginfo.com:
    url: http://localhost:7054
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org1.cfginfo.com/ca/ca.org1.cfginfo.com-cert.pem
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.cfginfo.com

  ca.org2.cfginfo.com:
    url: http://localhost:8054
    tlsCACerts:
      path: ${GOPATH}/src/blockchain-database/fixtures/crypto-config/peerOrganizations/org2.cfginfo.com/ca/ca.org2.cfginfo.com-cert.pem
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org2.cfginfo.com


entityMatchers:
  peer:
    - pattern: (\w*)peer0.org1.cfginfo.com(\w*)
      urlSubstitutionExp: grpcs://localhost:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.cfginfo.com
      mappedHost: peer0.org1.cfginfo.com

    - pattern: (\w*)peer1.org1.cfginfo.com(\w*)
      urlSubstitutionExp: grpcs://localhost:8051
      sslTargetOverrideUrlSubstitutionExp: peer1.org1.cfginfo.com
      mappedHost: peer1.org1.cfginfo.com

    - pattern: (\w*)peer0.org2.cfginfo.com(\w*)
      urlSubstitutionExp: grpcs://localhost:9051
      sslTargetOverrideUrlSubstitutionExp: peer0.org2.cfginfo.com
      mappedHost: peer0.org2.cfginfo.com

    - pattern: (\w*)peer1.org2.cfginfo.com(\w*)
      urlSubstitutionExp: grpcs://localhost:10051
      sslTargetOverrideUrlSubstitutionExp: peer1.org2.cfginfo.com
      mappedHost: peer1.org2.cfginfo.com

  orderer:
    - pattern: (\w*)orderer0.cfginfo.com(\w*)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer0.cfginfo.com
      mappedHost: orderer0.cfginfo.com

    - pattern: (\w*)orderer1.cfginfo.com(\w*)
      urlSubstitutionExp: localhost:8050
      sslTargetOverrideUrlSubstitutionExp: orderer1.cfginfo.com
      mappedHost: orderer1.cfginfo.com

    - pattern: (\w*)orderer2.cfginfo.com(\w*)
      urlSubstitutionExp: localhost:9050
      sslTargetOverrideUrlSubstitutionExp: orderer2.cfginfo.com
      mappedHost: orderer2.cfginfo.com

  certificateAuthorities:
    - pattern: (\w*)ca.org1.cfginfo.com(\w*)
      urlSubstitutionExp: http://localhost:7054
      mappedHost: ca.org1.cfginfo.com

    - pattern: (\w*)ca.org2.cfginfo.com(\w*)
      urlSubstitutionExp: http://localhost:8054
      mappedHost: ca.org2.cfginfo.com
